=== FrankX0/smartmeter/doc/powerProfile.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:annotation>
		<xs:documentation>
    		Antwort des ComModuls auf getPowerProfile-Requests
    	</xs:documentation>
	</xs:annotation>
	<xs:element name="values" type="t_values"/>
	<xs:complexType name="t_values">
		<xs:sequence>
			<xs:element name="header" type="t_header"/>
			<xs:choice>
				<xs:element name="v" type="xs:string" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="error" type="t_error" minOccurs="0"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="t_header">
		<xs:sequence>
			<xs:element name="name">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Wirkleistung"/>
						<xs:enumeration value="ERR"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="obis">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="1-1:16.7.0"/>
						<xs:enumeration value="ERR"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="startts">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[0-9]{12}[nws]?"/>
						<xs:pattern value="ERR"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="endts">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[0-9]{12}[nws]?"/>
						<xs:pattern value="ERR"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="samplerate">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[1-9]{1}[0-9]*"/>
						<xs:pattern value="ERR"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="no">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[0-9]+"/>
						<xs:pattern value="ERR"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="error" type="xs:boolean"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="t_error">
		<xs:sequence>
			<xs:element name="id">
				<xs:simpleType>
					<xs:restriction base="xs:nonNegativeInteger">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="9999"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="text" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== FrankX0/smartmeter/SmartMeterTests/getPowerProfileTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<values xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/InstantView/request/powerProfile.xsd">
	<header>
		<name>Wirkleistung</name>
		<obis>1.25.0</obis>
		<startts>160102171309w</startts>
		<endts>160102171449w</endts>
		<samplerate>1</samplerate>
		<no>100</no>
		<error>false</error>
	</header>
	<v>550</v>
	<v>554</v>
	<v>572</v>
	<v>566</v>
	<v>563</v>
	<v>564</v>
	<v>554</v>
	<v>574</v>
	<v>565</v>
	<v>573</v>
	<v>572</v>
	<v>568</v>
	<v>557</v>
	<v>573</v>
	<v>563</v>
	<v>553</v>
	<v>552</v>
	<v>545</v>
	<v>544</v>
	<v>545</v>
	<v>558</v>
	<v>549</v>
	<v>546</v>
	<v>543</v>
	<v>543</v>
	<v>542</v>
	<v>546</v>
	<v>543</v>
	<v>543</v>
	<v>542</v>
	<v>546</v>
	<v>550</v>
	<v>543</v>
	<v>549</v>
	<v>542</v>
	<v>548</v>
	<v>553</v>
	<v>545</v>
	<v>543</v>
	<v>627</v>
	<v>1150</v>
	<v>543</v>
	<v>547</v>
	<v>545</v>
	<v>542</v>
	<v>542</v>
	<v>1227</v>
	<v>543</v>
	<v>543</v>
	<v>542</v>
	<v>551</v>
	<v>545</v>
	<v>546</v>
	<v>544</v>
	<v>549</v>
	<v>547</v>
	<v>549</v>
	<v>545</v>
	<v>545</v>
	<v>543</v>
	<v>544</v>
	<v>547</v>
	<v>551</v>
	<v>543</v>
	<v>543</v>
	<v>546</v>
	<v>545</v>
	<v>546</v>
	<v>545</v>
	<v>546</v>
	<v>547</v>
	<v>544</v>
	<v>544</v>
	<v>550</v>
	<v>546</v>
	<v>557</v>
	<v>545</v>
	<v>571</v>
	<v>552</v>
	<v>546</v>
	<v>543</v>
	<v>547</v>
	<v>545</v>
	<v>545</v>
	<v>541</v>
	<v>542</v>
	<v>538</v>
	<v>540</v>
	<v>537</v>
	<v>540</v>
	<v>538</v>
	<v>537</v>
	<v>535</v>
	<v>537</v>
	<v>537</v>
	<v>537</v>
	<v>536</v>
	<v>536</v>
	<v>538</v>
	<v>538</v>
</values>
